ent/renovate: add troubleshooting steps to postUpgradeTasks
The `make -C install/kubernetes ...` step is unexpectedly failing due to:

  Error: open /tmp/renovate/repos/github/isovalent/cilium/install/kubernetes/cilium/values.yaml.tmpl: no such file or directory

As I cannot figure out what's wrong there, let's try to output the
content of these directories, to see whether the files got filtered
out for some unexpected reason...

Signed-off-by: Marco Iorio <marco.iorio@isovalent.com>