privnet/tests: ensure kubevirt CRD is ready
Explicitly wait for the kubevirt CRD to be established, before creating
the kubevirt instance. This prevents a possible failure along the lines of:

> error: resource mapping not found for name: "kubevirt" namespace: "" from  "...":
    no matches for kind "KubeVirt" in version "kubevirt.io/v1"

Related: b507eff104cf ("privnet: Ensure cert-manager CRDs are ready")
Signed-off-by: Marco Iorio <marco.iorio@isovalent.com>