Fix new golangci-lint findings
PR #45725 is updating `golangci-lint` from `v2.11.4` to `v2.12.1`. This
update brings new and updated linter rules, causing new failures, see
the golangci-lint [job](https://github.com/cilium/cilium/actions/runs/25504628804/job/74846790273?pr=45725) on that PR:
```
  Error: pkg/bpf/analyze/fields.go:19:30: inline: Constant reflect.Ptr should be inlined (govet)
  	if toValue.Type().Kind() != reflect.Ptr {
  	                            ^
  Error: pkg/bpf/analyze/fields.go:65:8: inline: Constant reflect.Ptr should be inlined (govet)
  		case reflect.Ptr:
  		     ^
  Error: pkg/bpf/constants.go:86:19: inline: Constant reflect.Ptr should be inlined (govet)
  	if typ.Kind() == reflect.Ptr {
  	                 ^
  Error: cilium-cli/install/install.go:194:6: slicesbackward: backward loop over slice can be modernized using slices.Backward (modernize)
  	for i := len(versions) - 1; i >= 0; i-- {
  	    ^
  Error: cilium-cli/internal/helm/helm.go:220:6: slicesbackward: backward loop over slice can be modernized using slices.Backward (modernize)
  	for i := len(versions) - 1; i >= 0; i-- {
  	    ^
  Error: daemon/cmd/endpoint_restore.go:542:6: slicesbackward: backward loop over slice can be modernized using slices.Backward (modernize)
  	for i := len(state.restored) - 1; i >= 0; i-- {
  	    ^
  Error: pkg/datapath/linux/route/route.go:38:15: the "prefix" key should be a constant (sloglint)
  		slog.String("prefix", r.Prefix.String()),
  		            ^
  Error: pkg/datapath/linux/route/route.go:39:15: the "nexthop" key should be a constant (sloglint)
  		slog.String("nexthop", nexthop),
  		            ^
  Error: pkg/datapath/linux/route/route.go:40:15: the "local" key should be a constant (sloglint)
  		slog.String("local", r.Local.String()),
  		            ^
  Error: pkg/endpoint/log_test.go:59:56: the "testField" key should be a constant (sloglint)
  	ep.PolicyDebug("PolicyDebug with fields", slog.String("testField", "Test Value"))
  	                                                      ^
  Error: pkg/logging/slog.go:96:14: the "" key should be a constant (sloglint)
  				Key:   a.Key,
  				         ^
  Error: pkg/logging/slog.go:101:14: the "" key should be a constant (sloglint)
  				Key:   a.Key,
  				         ^
  Error: pkg/logging/slog.go:107:13: the "" key should be a constant (sloglint)
  			Key:   a.Key,
  			         ^
  13 issues:
  * govet: 3
  * modernize: 3
  * sloglint: 7
```

This PR fixes those so we can unblock #45725.

Note: similar PRs updating golangci-lint in stable beanches also have
the same issue, we'll have to decide how we want to deal with those (fix
the findings or pin golangci-lint in stable branches):
* 1.17: #45876 ([job](https://github.com/cilium/cilium/actions/runs/25616356556/job/75195050146?pr=45876))
* 1.18: #45831 ([job](https://github.com/cilium/cilium/actions/runs/25504496824/job/74846237289?pr=45831))
* 1.19: #45468 ([job](https://github.com/cilium/cilium/actions/runs/25641666457/job/75263043810?pr=45468))

Signed-off-by: Hadrien Patte <hadrien.patte@datadoghq.com>