contrib: fix typo in identity_is_node.cocci
[ upstream commit 76b2417357f06e83e57679ce5cd66b40e0b00068 ]

Traceback (most recent call last):
  File "<string>", line 3, in <module>
NameError: name 'p2' is not defined. Did you mean: 'p1'?
EXN: Failure("Error in Python script, line 19, file \"<snip>/cilium/contrib/coccinelle/identity_is_node.cocci\": Python failure") in ./lib/identity.h

Fixes: b9444865a5ad ("bpf: remove unused identity_is_node()")
Signed-off-by: Julian Wiedmann <jwi@isovalent.com>
Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>