enterprise/ingresspolicy: explicity add and remove identity
An upcoming change being synced in[^1] will get rid of the implicit
addition of identities to the identity manager on lookup through
policyRepository.GetSelectorPolicy. This causes the ingress policy unit
tests to fail, e.g.:

--- FAIL: Test_ingressPolicyManager_DeleteIngressPolicy/successfully_remove_existing_policy (0.00s)

    ingress_policy_test.go:160:
        	Error Trace:	/home/runner/work/cilium/cilium/enterprise/pkg/ingresspolicy/ingress_policy_test.go:160
        	Error:      	Received unexpected error:
        	            	failed to get selector policy default/cec SelectorPolicy not found in cache for ID 16777216
        	Test:       	Test_ingressPolicyManager_DeleteIngressPolicy/successfully_remove_existing_policy

Fix this by explicitly adding the ingress policy identity to the
identity manager in EnsureIngressPolicy and remove it again in
DeleteIngressPolicy.

Ref. https://isovalent.slack.com/archives/C02HD9CHL0P/p1764753071854289

[^1]: https://github.com/cilium/cilium/pull/42661

Signed-off-by: Tobias Klauser <tobias@isovalent.com>