helm: Avoid secrets creation in preflight
Do not attempt to create secrets namespacse during the preflight setup
because these namespaces may be owned by an existing real installation
of Cilium. Attempting to create them from the preflight Helm release
results in the conflict message:

  Error: Unable to install Cilium: Unable to continue with install:
    Namespace "cilium-secrets" in namespace "" exists and cannot be imported
    into the current release: invalid ownership metadata;
    annotation validation error: key "meta.helm.sh/release-name" must equal
    "cilium-preflight": current value is "cilium"

Signed-off-by: Joe Stringer <joe@cilium.io>