pkg/maps: Use programmed name in nodeMapV2 init
The preceding commit in this series got rid of these lines in the loader
test (loader_test.go):

tb.Cleanup(func() {
	require.NoError(tb, os.RemoveAll(bpf.TCGlobalsPath()))
	require.NoError(tb, os.RemoveAll(bpf.CiliumPath()))
})

which would have previously cleaned up any maps in the TCGlobalsPath.
Removing this in the loader test seems to have revealed this issue which
was previously masked in TestPrivilegedNodeMapV2.

TestPrivilegedNodeMapV2 tries to create a new map called
test_cilium_node_map_v2, but nodeMapV2's init calls LoadRegisterMap
with MapNameV2 ("cilium_node_map_v2"), so if any garbage is leftover
from other tests you get this failure:

node_map_v2_privileged_test.go:49:
    	Error Trace:	/host/pkg/maps/nodemap/node_map_v2_privileged_test.go:49
    	Error:      	Should be empty, but was map[43672:10.0.2.15]
    	Test:       	TestPrivilegedNodeMapV2

To fix this, make sure init uses the original name passed to newMapV2.

Signed-off-by: Jordan Rife <jrife@google.com>