Revert ".github/actions/e2e: Fix incorrect devices helm option syntax"
This reverts commit 8b3f6fafd528fc1463e3afecc02ced4e2a42eee0.

https://github.com/cilium/cilium/actions/runs/25667171203/job/75342711211

Error: Unable to install Cilium: failed parsing --set data: key "eth1" has no value

The "eth0,eth1" wasn't properly quoted. Let's just just revert back
to the original form.

Signed-off-by: Jussi Maki <jussi@isovalent.com>