bpf/lib/lb.h: Fix active connection tracking + IPv6
When both IPv6 and active connection tracking are enabled, we are unable
to compile, resulting in the following error:

```
./lib/lb.h:1071:21: error: use of undeclared identifier 'ct_state'
```

This is because in `lb6_local` the name of the variable is `state` not
`ct_state`. This issue seems to have been here since the introduction
of the feature and was never caught due to a lack of testing.

Signed-off-by: Dylan Reimerink <dylan.reimerink@isovalent.com>