ilb: fix udpproxy session test name
This commit fixes the name of the udpproxy session test.

It's overlapping with the name of the udpproxy base test.

This might be the reason why this test is failing quite often in CI.

e.g. https://github.com/isovalent/cilium/actions/runs/13416748433/job/37483372924

```
=== RUN   Test UDPProxy force mode t1-only
Creating backend apps...
Creating clients and add BGP peering ...
Creating LB VIP resources...
Creating LB BackendPool resources...
Creating LB Service resources...
Waiting for full VIP connectivity of "udp-proxy-t1-only"...

Error: failed to wait for VIP (udp-proxy-t1-only): timeout reached waiting for LBVIP udp-proxy-t1-only to get VIP assigned (last error: %!w(<nil>))
Error: Process completed with exit code 1.
```

Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>