k8s/apis/isovalent.com/v1alpha1: validate INP order as float
The INP rule order field is of type float but currently it's attempted
to be validated as an int. This causes the following error on operator
startup:

    time="2025-04-08T12:29:57.673943695Z" level=fatal msg="unable to create CRDs: Unable to create custom resource definition: CustomResourceDefinition.apiextensions.k8s.io \"isovalentnetworkpolicies.isovalent.com\" is invalid: [spec.validation.openAPIV3Schema.properties[spec].x-kubernetes-validations[0].rule: Invalid value: apiextensions.ValidationRule{Rule:\"!has(self.order) || self.order >= 0\", Message:\"Order must be >= 0\", MessageExpression:\"\"}: compilation failed: ERROR: <input>:1:32: found no matching overload for '_>=_' applied to '(double, int)'\n | !has(self.order) || self.order >= 0\n | ...............................^, spec.validation.openAPIV3Schema.properties[specs].items.x-kubernetes-validations[0].rule: Invalid value: apiextensions.ValidationRule{Rule:\"!has(self.order) || self.order >= 0\", Message:\"Order must be >= 0\", MessageExpression:\"\"}: compilation failed: ERROR: <input>:1:32: found no matching overload for '_>=_' applied to '(double, int)'\n | !has(self.order) || self.order >= 0\n | ...............................^]" subsys=cilium-operator-generic

Adjust the validation expression to use float comparision to fix the
error.

Reported-by: Julian Wiedmann <jwi@isovalent.com>
Signed-off-by: Tobias Klauser <tobias@isovalent.com>