hubble/enterprise: remove Go 1.18 constraint
This was making `go vet ./...` fail with
  hubble/enterprise/cmd/plugins.go:147:17: errors.Join requires go1.20
  or later (file is go1.18)

I'm not sure why `go test vet=all ./...` doesn't catch this, possibly
because there is no test?

Signed-off-by: David Bimmler <david.bimmler@isovalent.com>